demo/public/index.js, src/js/CroppingArea.js, src/js/PreviewCrop.js, src/js/index.js, src/templates/preview-crop.mustache, src/templates/wrapper.mustache
Integrates a preview mode that works with a static cropping area
=> Preview crop functionality

demo/public/index.html, demo/public/index.js, src/js/PreviewCrop.js, src/js/index.js, src/templates/wrapper.mustache
Makes it easier to extend the config with new datapoints necessary for previewCrop
=> PreviewCrop: Easier to manage config

src/js/CroppingArea.js, src/js/index.js
Note: This will be removed when mir image url responses contain contain a header that allows access from all origins.
=> CroppingArea: Flag to control broadcasting

src/js/CroppingArea.js
If the user knows the scale ahead of time, then can perform whatever transformation is necessary to pass in the much saner `coordinates: { x, y, scale }` signature for initial image coordinates. If they pass in a `width` and `height` with their x and y, they can't possibly know what the scale is, so it can only be assumed that the `x` and `y` have also been converted into that unknown to the user scale.
This addresses the previous "bug" behavior of assuming the values would be in two different scales (`width and height` in one and `x and y` in another).
=> CroppingArea: If given initial width/height, scale x and y

.gitignore, demo/public/index.js, karma.conf.js, package.json, src/js/CroppingArea.js, src/js/ZoomSlider.js, src/js/index.js, src/templates/ratio-lock.mustache, src/templates/suggesstion-area.mustache, src/templates/zoom-slider.mustache, test/.jshintrc, test/lib/polyfills.js, test/specs/CroppingArea.js, test/specs/PreviewCrop.js, test/specs/RatioLock.js, test/specs/SuggestionArea.js, test/specs/UploadArea.js, test/specs/ZoomSlider.js, webpack.config.js
- Switch from starting the image at the max scale (smallest generated image) to
minimum scale (largest generated image)
- Add the ability to define a displayed width and a warning when scaling if the
generated width will be smaller than the displayed width
=> Cropper: Better UX around image scale

src/js/CroppingArea.js, src/js/index.js, test/specs/CroppingArea.js, test/specs/index.js
Addresses https://github.com/adobe-community/issues/issues/5160
=> CroppingArea: Guard against slow loading images

src/js/UploadArea.js, src/js/index.js, test/specs/index.js
fixes https://github.com/adobe-community/issues/issues/7968
Small change that shows the loading state of the cropper until the image is loaded.
=> Show loading state until image is loaded

src/js/CroppingArea.js
The cropping area is constantly off by one. These changes fix some of the math errors that causes it to be in that state.
Fixes https://github.com/adobe-community/issues/issues/9774
**Note:** Lacks testing as testing canvas is really hard. Have an issue to backfill tests for cropping area in the near future (https://github.com/adobe-community/issues/issues/9903)
=> CroppingArea: Fix bounding area off-by-ones

.babelrc, .travis.yml, package.json, webpack.config.js
This reverts commit bab26b30f82ada805b341eb08fbf855e9ce4389b.
=> Revert "Update to babel 6 (#40)"

src/js/SuggestionArea.js, src/js/index.js, test/specs/SuggestionArea.js
Addresses: https://github.com/adobe-community/issues/issues/14262
=> Suggestion Area: increase max number of suggestions from 7 to 8

src/templates/preview-crop.mustache
Add the class name for div, for project editor upload image styling in be.net.
=> add class name for styling

demo/index.js, src/js/CroppingArea.js, src/js/index.js, test/specs/CroppingArea.js, test/specs/index.js, webpack.config.js
We do this calculation everywhere we perform a crop. This moves the logic into helicropter itself and added bound checking to make sure we never make the image larger than it's native size.
=> crop: Add scaled dimensions to crop data

demo/index.js, src/js/UploadArea.js, src/js/index.js, src/templates/upload-area.mustache, test/specs/UploadArea.js, test/specs/index.js
Resolves adobe-community/issues/issues/23903
=> Hides Upload area's upload button on #uploadThenRender

src/js/UploadArea.js, src/js/index.js, src/templates/upload-area.mustache, test/specs/UploadArea.js, test/specs/index.js
Resolves adobe-community/issues/issues/23904
=> Loader style: either progressbar or spinner

src/js/index.js, test/specs/index.js
Resolves adobe-community/issues/issues/23965
=> Returns correctly scaled cropped image

src/js/CroppingArea.js, src/js/index.js, test/specs/CroppingArea.js
=> Blurry image text: override the default if it is set

src/js/CroppingArea.js, src/js/ZoomSlider.js, src/js/index.js, test/specs/CroppingArea.js, test/specs/ZoomSlider.js, test/specs/index.js
Ref adobe-community/issues/issues/24850
=> Pause controls when min scale is same as max scale

package.json, src/js/UploadArea.js, src/js/index.js, test/specs/UploadArea.js, test/specs/index.js
Ref: adobe-community/issues/issues/24285
Ref: https://github.com/behance/BeFF/pull/206
=> Emit image:processing when it's correcting image rotation

src/js/CroppingArea.js, test/specs/CroppingArea.js
Ref adobe-community/issues/issues/25155
=> cropping area: getCropData to return correct width & height to calculate scaled value

src/js/CroppingArea.js, src/js/UploadArea.js, src/js/index.js, test/specs/UploadArea.js, test/specs/index.js
Ref: adobe-community/issues/issues/24848
=> Scales uploader view on image upload

demo/index.js, src/js/CroppingArea.js, src/js/index.js, test/specs/CroppingArea.js
Ref: adobe-community/issues/issues/24747
1. Adds different background types for the cropper: transparent pattern, solid color, blurry image.
2. Locks X and Y pan of the image only if there isn't enough room to pan with allowLetterboxing.
3. Returns correct dimensions for letterbox mode.
=> Cropper: new background types, solid, transparent, blurry image

src/js/CroppingArea.js, test/specs/CroppingArea.js
=> CroppingArea: redraw background layer on set-image

src/js/index.js, test/specs/index.js
ref: adobe-community/issues/issues/23789
=> emit slider:changed event
